/* Modelagem Básica - ENTIDADE = TABELA*/

CLIENTE 
NOME - CHARACTER(30)
CPF - NUMERIC(11)
EMAIL - CHARACTER(30)
TELEFONE - CHARACTER(30)
ENDERECO - CHARACTER(100)
SEXO - CHARACTER(1)

/* PROCESSOS DE MODELAGEM */

/* FASE 01 E 02 - AD ADM DE DADOS */

MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM

/* FASE 03 - DBA / AD */

MODELAGEM FÍSICA - SCRIPTS DE BANCO

